### ISSUE TITLE
Normalise transaction randomization

### ISSUE THREAD

**Issue by proletesseract** [NAVCoin/navtech#29]
Output transactions are currently rounded to 8 decimal places.

Round the random transactions to more normal transaction values.

Perhaps 1 NAV or 0.5 NAV

**Comment by mogrith** [comment]
Do you have access to USD or EUR Value? round to .01 of fiat would mimic a Nav TX to coinpayments
sending Nav as Nav would be more likely rounded to a .5 Nav, But If I'm sending 19.95EUR it would be a longer length
